[meta]
version = 1
name = "Gruvbox Material Dark"
description = "Gruvbox material dark palette"
variant = "dark"
inherits = "gruvbox-dark"
icon = "/usr/share/vicinae/themes/icons/gruvbox.png"

[colors.core]
accent = "#A9B665"
background = "#1d2021"
secondary_background = "#141617"
foreground = "#ebdbb2"
border = "#32302F"

[colors.list.item.selection]
background = "#32302F"
# secondary_background = "#524943"

[colors.accents]
blue = "#458588"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
yellow = "#d79921"
cyan = "#689d6a"
