# Matugen Hyprland Colors

$background = rgb(1a110f)

$error = rgb(ffb4ab)

$error_container = rgb(93000a)

$inverse_on_surface = rgb(392e2b)

$inverse_primary = rgb(8f4c36)

$inverse_surface = rgb(f1dfda)

$on_background = rgb(f1dfda)

$on_error = rgb(690005)

$on_error_container = rgb(ffdad6)

$on_primary = rgb(55200d)

$on_primary_container = rgb(ffdbd0)

$on_primary_fixed = rgb(390b00)

$on_primary_fixed_variant = rgb(723521)

$on_secondary = rgb(442a21)

$on_secondary_container = rgb(ffdbd0)

$on_secondary_fixed = rgb(2c160e)

$on_secondary_fixed_variant = rgb(5d4036)

$on_surface = rgb(f1dfda)

$on_surface_variant = rgb(d8c2bc)

$on_tertiary = rgb(3a3005)

$on_tertiary_container = rgb(f4e2a7)

$on_tertiary_fixed = rgb(221b00)

$on_tertiary_fixed_variant = rgb(52461a)

$outline = rgb(a08d87)

$outline_variant = rgb(53433f)

$primary = rgb(ffb59e)

$primary_container = rgb(723521)

$primary_fixed = rgb(ffdbd0)

$primary_fixed_dim = rgb(ffb59e)

$scrim = rgb(000000)

$secondary = rgb(e7bdb1)

$secondary_container = rgb(5d4036)

$secondary_fixed = rgb(ffdbd0)

$secondary_fixed_dim = rgb(e7bdb1)

$shadow = rgb(000000)

$source_color = rgb(4c2d23)

$surface = rgb(1a110f)

$surface_bright = rgb(423733)

$surface_container = rgb(271d1b)

$surface_container_high = rgb(322825)

$surface_container_highest = rgb(3d322f)

$surface_container_low = rgb(231917)

$surface_container_lowest = rgb(140c0a)

$surface_dim = rgb(1a110f)

$surface_tint = rgb(ffb59e)

$surface_variant = rgb(53433f)

$tertiary = rgb(d7c68d)

$tertiary_container = rgb(52461a)

$tertiary_fixed = rgb(f4e2a7)

$tertiary_fixed_dim = rgb(d7c68d)

